version: '3.9'
     
services:

  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567

  spring-app:
    build: 
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
    
    depends_on:
      - db
  spa-app:
    build: 
      context: ./imagelite
      dockerfile: Dockerfile
    ports:
      - "9090:3000"
    depends_on:
      - spring-app

