

spring:
    datasource:
       
        url: jdbc:sqlserver://pjblpucpr24.database.windows.net:1433;database=pjblpucpr24;user=sqlserver;password=Gui1234567;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  
    jpa: 
        
        database: SQL_SERVER
        hibernate: 
            ddl-auto: update
             
        show-sql: true
    servlet:
        multipart: 
            max-file-size: 20MB
            max-request-size: 20MB