#jdbc:postgresql://localhost:5432/imagelite

spring:
    datasource:
        #url: jdbc:postgresql://db:5432/db
        url: jdbc:sqlserver://pjblpucpr24.database.windows.net:1433;database=pjblpucpr24;user=sqlserver@pjblpucpr24;password=Gui1234567encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

    jpa: 
        database: POSTGRESQL
        hibernate: 
            ddl-auto: update
        show-sql: true
    servlet:
        multipart: 
            max-file-size: 20MB
            max-request-size: 20MB